service: Menu
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [MenuTable, Arn]

functions:
  addMenu:
    handler: src/handlers/addMenu.handler
    description: Post method to add new commands to the list of commands
    events:
      - httpApi:
          path: /
          method: post

  fetchMenus:
    handler: src/handlers/fetchMenus.handler
    description: Get method to scan dynamodb and return all the commands in the database
    events:
      - httpApi:
          path: /menus
          method: get

  fetchMenu:
    handler: src/handlers/fetchMenu.handler
    description: Get method with inut as specific 'id' to get the detais of the specific item
    events:
      - httpApi:
          path: /menu/{id}
          method: get

  updateMenu:
    handler: src/handlers/updateMenu.handler
    description: Update method to modify the commands if there are any changes
    events:
      - httpApi:
          path: /menu/{id}
          method: put

  deleteMenu:
    handler: src/handlers/deleteMenu.handler
    description: Delete method to clear the item specified in by it's "id" number
    events:
      - httpApi:
          path: /menu/{id}
          method: delete

resources:
  Resources:
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MenuTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
